'use client'
import "./globals.css";
import 'antd/dist/reset.css';
import { Inter } from "next/font/google";
import { Breadcrumb, Layout, Menu, MenuProps } from "antd";
import { LaptopOutlined, NotificationOutlined, UserOutlined } from '@ant-design/icons';
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const items2: MenuProps['items'] = [UserOutlined, LaptopOutlined, NotificationOutlined].map(
  (icon, index) => {
    const key = String(index + 1);

    return {
      key: `sub${key}`,
      icon: React.createElement(icon),
      label: `价格录入`,
      
      // children: new Array(4).fill(null).map((_, j) => {
      //   const subKey = index * 4 + j + 1;
      //   return {
      //     key: subKey,
      //     label: `option${subKey}`,
      //   };
      // }),
    };
  },
);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const navItem = [
    {
      key: '1',
      label: '浙江一区'
    }
  ]
  const menuItem = [{
    key: `1`,
    icon: React.createElement(UserOutlined),
    label: `价格录入`,
  },{
    key: '2',
    icon: React.createElement(LaptopOutlined),
    label: '数据面板'
  },{
    key: '3',
    icon: React.createElement(NotificationOutlined),
    label: '装备录入'
  }]
  const { Header, Content, Sider, Footer } = Layout;
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
        <Layout className="container">
          <Header style={{ display: "flex", alignItems: "center" }}>
            <div className="demo-logo" />
            <Menu
              theme="dark"
              mode="horizontal"
              defaultSelectedKeys={["2"]}
              items={navItem}
            />
          </Header>
          <Content style={{ padding: "0 50px"}}>
            <Breadcrumb style={{ margin: "16px 0" }}>
              <Breadcrumb.Item>Home</Breadcrumb.Item>
              <Breadcrumb.Item>List</Breadcrumb.Item>
              <Breadcrumb.Item>App</Breadcrumb.Item>
            </Breadcrumb>
            <Layout>
              <Sider  width={300}>
                <Menu
                  mode="inline"
                  defaultSelectedKeys={["1"]}
                  defaultOpenKeys={["sub1"]}
                  style={{ height: "100%" }}
                  items={menuItem}
                />
              </Sider>
              {children}
              
            </Layout>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            Ant Design ©2023 Created by Ant UED
          </Footer>
        </Layout>
        </div>
        </body>
    </html>
  )
}
